api/urls.py
from django.urls import path, include
from rest_framework.urlpatterns import format_suffix_patterns
from api.views import (user_view, company_view, 
                       document_view, post_view, 
                       product_view, service_view,
                       comment_view, follow_view
                       )
from rest_framework.routers import DefaultRouter

app_name = "api"

# Create a router and register our ViewSets with it.
router = DefaultRouter()
router.register(r'companies', company_view.CompanyViewSet, basename='company')
router.register(r'users', user_view.UserViewSet, basename='user')
router.register(r'genders', user_view.GenderViewSet, basename='gender')
router.register(r'company-categories', company_view.CompanyCategoryViewSet, basename='company-category')
router.register(r'company-sizes', company_view.CompanySizeViewSet, basename='company-size')
router.register(r'documents', document_view.DocumentViewSet, basename='document')
router.register(r'document-types', document_view.DocumentTypeViewSet, basename='document-type')
router.register(r'posts', post_view.PostViewSet, basename='post')
router.register(r'products', product_view.ProductViewSet, basename='product')
router.register(r'product-images', product_view.ProductImageViewSet, basename='product-image')
router.register(r'product-categories', product_view.ProductCategoryViewSet, basename='product-category')
router.register(r'services', service_view.ServiceViewSet, basename='service')
router.register(r'service-images', service_view.ServiceImageViewSet, basename='service-image')
router.register(r'service-categories', service_view.ServiceCategoryViewSet, basename='service-category')
router.register(r'likes', follow_view.LikeViewSet, basename='like')
router.register(r'comments', comment_view.CommentViewSet, basename='comment')
router.register(r'follows', follow_view.FollowViewSet, basename='follow')
urlpatterns = [
    path('', include(router.urls)),
    
]

authentication/models.py
from django.db import models
from wagtail.fields import RichTextField
# Create your models here.
from django.contrib.auth.models import AbstractUser
from wagtail.snippets.models import register_snippet
from wagtail.admin.panels import FieldPanel, InlinePanel, FieldRowPanel, MultiFieldPanel, PageChooserPanel
from django.utils.translation import gettext_lazy as _
from django.utils.text import slugify
from django.urls import reverse
from django.contrib.auth.models import BaseUserManager, AbstractBaseUser, PermissionsMixin

class Gender(models.Model):
    type = models.CharField(max_length=500, null=True, blank= True)

    def __str__(self):
        return f'{self.type}'

class MyUserManager(BaseUserManager):
    def create_user(self, email, password=None):
        """
        Creates and saves a User with the given email and password.
        """
        if not email:
            raise ValueError("Users must have an email address")

        user = self.model(
            email=self.normalize_email(email),
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password=None):
        """
        Creates and saves a superuser with the given email, date of
        birth and password.
        """
        user = self.create_user(
            email,
            password=password,
        )
        user.is_admin = True
        user.save(using=self._db)
        return user
class User(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(verbose_name='email', max_length=255, unique=True)
    first_name = models.CharField(verbose_name='First Name', max_length=255, null=True, blank=True)
    last_name = models.CharField(verbose_name='Last Name', max_length=255, null=True, blank=True)
    gender = models.ForeignKey(Gender, on_delete=models.DO_NOTHING, null=True, blank=True)
    date_of_birth = models.DateField(null=True, blank=True)
    bio = RichTextField(null=True, blank=True)
    role = models.CharField(max_length=500, null=True, blank=True)
    company = models.CharField(max_length=500, null=True, blank=True)
    phone_number = models.CharField(max_length=255, null=True, blank=True)
    verified = models.BooleanField(default=False)
    date_joined = models.DateTimeField(verbose_name='date joined', auto_now_add=True, null=True)
    last_login = models.DateTimeField(verbose_name='last login', auto_now=True, null=True)
    country = models.CharField(verbose_name='country', max_length=255, null=True, blank=True)
    region = models.CharField(verbose_name='region', max_length=255, null=True, blank=True)
    city = models.CharField(verbose_name='country', max_length=255, null=True, blank=True)
    address = models.CharField(max_length=255, null=True, blank=True)
    avatar = models.ImageField(null=True, blank=True)
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)

    objects = MyUserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []
    
    @property
    def full_name(self):
        return f'{self.first_name} {self.last_name}'

    def __str__(self):
        return f'{self.email}'

waitlist/models.py
# Create your models here.
from django.db import models
from wagtail.fields import RichTextField
from wagtail.models import Page
from django.shortcuts import render
from wagtail.contrib.settings.models import BaseSiteSetting, register_setting
from wagtail.admin.panels import FieldPanel, InlinePanel, FieldRowPanel, MultiFieldPanel, PageChooserPanel
from wagtail.contrib.forms.models import AbstractEmailForm, AbstractFormField
from wagtail.snippets.models import register_snippet
from modelcluster.fields import ParentalKey
from wagtail.contrib.forms.panels import FormSubmissionsPanel



   
class WaitlistFormField(AbstractFormField):
    page = ParentalKey('WaitlistFormPage', on_delete=models.CASCADE, related_name='form_fields')

class WaitlistFormPage(AbstractEmailForm):
    template = 'waitlist/waitlist_form.html'
    intro = RichTextField(blank=True)
    thank_you_text = RichTextField(blank=True)
    content_panels = AbstractEmailForm.content_panels + [
        FormSubmissionsPanel(),
        FieldPanel('intro'),
        InlinePanel('form_fields', label="Form fields"),
        FieldPanel('thank_you_text'),
        MultiFieldPanel([
            FieldRowPanel([
                FieldPanel('from_address', classname="col6"),
                FieldPanel('to_address', classname="col6"),
            ]),
            FieldPanel('subject'),
        ], "Email"),
    ]

    def serve(self, request, *args, **kwargs):
        if request.method == 'POST':
            form = self.get_form(request.POST, page=self, user=request.user)

            if form.is_valid():
                self.process_form_submission(form)
                
                # Update the original landing page context with other data
                landing_page_context = self.get_context(request)
                landing_page_context['email'] = form.cleaned_data['email']

                return render(
                    request,
                    self.get_landing_page_template(request),
                    landing_page_context
                )
        else:
            form = self.get_form(page=self, user=request.user)

        context = self.get_context(request)
        context['form'] = form
        return render(
            request,
            self.get_template(request),
            context
        )

@register_setting
class WaitlistFormSettings(BaseSiteSetting):
    waitlist_form_page = models.ForeignKey(
        'wagtailcore.Page', null=True, on_delete=models.SET_NULL)

    panels = [
        # note the page type declared within the pagechooserpanel
        PageChooserPanel('waitlist_form_page', ['waitlist.WaitlistFormPage']),
    ]


from django.db import models

from wagtail.models import Page
from wagtail.fields import RichTextField
from wagtail.admin.panels import FieldPanel
class LearnMore(Page):
    template = 'waitlist/learn_more.html'
    max_count = 1
    body = RichTextField(blank=True)

    content_panels = Page.content_panels + [
        FieldPanel('body'),
    ]


@register_setting
class ImportantPages(BaseSiteSetting):
    # Fetch these pages when looking up ImportantPages for or a site
    select_related = ["about", "home"]

    about = models.ForeignKey(
        'wagtailcore.Page', null=True, on_delete=models.SET_NULL, related_name='+')
    
    home = models.ForeignKey(
        'wagtailcore.Page', null=True, on_delete=models.SET_NULL, related_name='+')

    panels = [
        PageChooserPanel('about', ['waitlist.LearnMore']),
        PageChooserPanel('home', ['home.HomePage']),
    ]

authentication/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _

from wagtail.users.forms import UserEditForm, UserCreationForm

from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.utils.translation import gettext_lazy as _
# from django.contrib.auth.models import User
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import (
    AuthenticationForm,
)
from authentication.models import User


class UserSignInForm(AuthenticationForm):
    email = forms.EmailField(widget=forms.EmailInput(attrs={'placeholder': 'Email'}), label='Email')
    password = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Password..'}), label='Password')

    class Meta:
        model = User
        fields = ['email', 'password']

class UserRegisterForm(UserCreationForm):
    """
        Creates User registration form for signing up.
    """
    def __init__(self, *args, **kwargs):
        super(UserRegisterForm, self).__init__(*args, **kwargs)
        # self.fields['username'].widget.attrs.pop("autofocus", None)

    email = forms.EmailField(max_length=254, required=True, widget=forms.EmailInput(attrs={
        "name": "email", "class": "input100",
        "placeholder": "Email"
    }
    ),
        help_text='Required. Input a valid email address.'
    )
    password1 = forms.CharField(label="Password",
    widget=forms.PasswordInput(attrs={
        "name": "password", "class": "input100",
        "placeholder": "Password"
    }
    ),
    )

    password2 = forms.CharField(label="Confirm Password",
                                help_text=_(
                                    "Enter the same password as before, for verification."),
    widget=forms.PasswordInput(attrs={"name": "Confirm Password", "class": "input100", "placeholder": "Confirm Password"}),
    )

    class Meta:
        model = User
        fields = ['email', 'password1', 'password2']

    def save(self, commit=True):
        user = super(UserRegisterForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
        return user
    
class CustomUserEditForm(UserEditForm):
    email = forms.CharField(required=False, label=_("Email"))
    gender = forms.CharField(required=False, label=_("Gender"))
    date_of_birth = forms.DateField(required=False, label=_("Date of birth"))
    bio = forms.Textarea()
    role = forms.CharField(required=False, label=_("Role"))
    company = forms.CharField(required=False, label=_("Company"))
    verified = forms.BooleanField(required=True, label=_("Verified"))
    country = forms.CharField(required=False, label=_("Country"))
    region = forms.CharField(required=False, label=_("State"))
    city = forms.CharField(required=False, label=_("City"))
    phone_number = forms.CharField(required=False, label=_("Phone number"))
    address = forms.CharField(required=False, label=_("Residential address"))
    avatar = forms.ImageField(required=False, label=_("Avatar"))


class CustomUserCreationForm(UserCreationForm):
    email = forms.CharField(required=False, label=_("Email"))
    gender = forms.CharField(required=False, label=_("Gender"))
    date_of_birth = forms.DateField(required=False, label=_("Date of birth"))
    bio = forms.Textarea()
    role = forms.CharField(required=False, label=_("Role"))
    company = forms.CharField(required=False, label=_("Company"))
    verified = forms.BooleanField(required=True, label=_("Verified"))
    country = forms.CharField(required=False, label=_("Country"))
    region = forms.CharField(required=False, label=_("State"))
    city = forms.CharField(required=False, label=_("City"))
    phone_number = forms.CharField(required=False, label=_("Phone number"))
    address = forms.CharField(required=False, label=_("Residential address"))
    avatar = forms.ImageField(required=False, label=_("Avatar"))

waitlist/templates/waitlist/waitlist_form.html
{% load static wagtailcore_tags %} {% load static %} {% load waitlist_form %} {% get_waitlist_form as form %}


<form action="{% pageurl form.page %}" method="post">
    {% csrf_token %}
    <div class="row">
        <div class="col-sm-6 form-wrapper">
            <label for="id_first_name" class="form-label">First name</label>
            <input type="text" name="first_name" id="id_first_name" class="form-control" placeholder="Enter first name">
        </div>
        <div class="col-sm-6 form-wrapper">
            <label for="id_last_name" class="form-label">Last name</label>
            <input type="text" name="last_name" id="id_last_name" class="form-control" placeholder="Enter last name">
        </div>
        <div class="col-sm-6 form-wrapper">
            <label for="id_company" class="form-label">Company name</label>
            <input type="text" name="company" id="id_company" class="form-control" placeholder="Name of company">
        </div>
        <div class="col-sm-6 form-wrapper">
            <label for="id_email" class="form-label">Email</label>
            <input type="email" name="email" id="id_email" class="form-control" placeholder="name@company.com">
        </div>
        <div class="col-sm-6 form-wrapper">
            <label for="id_role" class="form-label">Role</label>
            <input type="text " name="role" id="id_role" class="form-control" placeholder="Your role in company">
        </div>
        <div class="col-sm-6 form-wrapper">
            <label for="id_remark" class="form-label">Remark</label> <textarea class="form-control" name="remark" id="id_remark" cols="30" rows="2" placeholder="Help make the product better."></textarea>
        </div>
    </div>
    <input type="submit" value="Join waitlist" class="btn btn-primary form-button">
</form>

waitlist/templates/waitlist/waitlist_form_landing.html
{% extends "base.html" %} {% load static %}{% load wagtailimages_tags %}{% load wagtailcore_tags %}



{% block content %}
<section class="home-hero">
    {% include 'header.html' %}
</section>
<div class="display-sign-container batch-container login-container" style="z-index: 1000;">
    <div class="card text-center">
        <!-- <svg width="420" height="328" viewBox="0 0 420 328" fill="none" xmlns="http://www.w3.org/2000/svg">
            <circle cx="213" cy="188" r="140" fill="#B9FFC0"/>
            <circle cx="213" cy="188" r="74" fill="#84FF90"/>
            <path fill-rule="evenodd" clip-rule="evenodd" d="M242.664 170.436C244.246 172.018 244.246 174.582 242.664 176.164L210.264 208.564C208.683 210.145 206.118 210.145 204.537 208.564L188.337 192.364C186.755 190.782 186.755 188.218 188.337 186.636C189.918 185.055 192.483 185.055 194.064 186.636L207.4 199.972L236.937 170.436C238.518 168.855 241.083 168.855 242.664 170.436Z" fill="white"/>
            <circle cx="25" cy="295" r="15" fill="url(#paint0_linear_0_1)"/>
            <circle cx="37.5" cy="37.5" r="37.5" fill="url(#paint1_linear_0_1)"/>
            <circle cx="270" cy="10" r="10" fill="url(#paint2_linear_0_1)"/>
            <circle cx="395" cy="195" r="25" fill="url(#paint3_linear_0_1)"/>
            <defs>
            <linearGradient id="paint0_linear_0_1" x1="40" y1="286.45" x2="10" y2="310" gradientUnits="userSpaceOnUse">
            <stop stop-color="#98FAC0"/>
            <stop offset="1" stop-color="#98FAC0" stop-opacity="0"/>
            </linearGradient>
            <linearGradient id="paint1_linear_0_1" x1="75" y1="16.125" x2="2.23517e-06" y2="75" gradientUnits="userSpaceOnUse">
            <stop stop-color="#98FAC0"/>
            <stop offset="1" stop-color="#98FAC0" stop-opacity="0"/>
            </linearGradient>
            <linearGradient id="paint2_linear_0_1" x1="280" y1="4.3" x2="260" y2="20" gradientUnits="userSpaceOnUse">
            <stop stop-color="#98FAC0"/>
            <stop offset="1" stop-color="#98FAC0" stop-opacity="0"/>
            </linearGradient>
            <linearGradient id="paint3_linear_0_1" x1="420" y1="180.75" x2="370" y2="220" gradientUnits="userSpaceOnUse">
            <stop stop-color="#98FAC0"/>
            <stop offset="1" stop-color="#98FAC0" stop-opacity="0"/>
            </linearGradient>
            </defs>
        </svg> -->
        <img src="/static/images/taxi-handshake.gif" alt="">
        <div class="card-body">
            <h5 class="card-title">Thank you for joining our wait list.</h5>
            <p class="card-text">You will be the first to hear from us.</p>
            <a href="/" class="btn btn-primary join-waitlist-btn" style="background: #F1C644; color: #000;">Home</a>
        </div>
    </div>
</div>
{% endblock %}